### PR TITLE
Update URLs from "http://www.weechat.org" to "https://weechat.org"

### PR DESCRIPTION
**Pull request by Zarthus**
Also bump all versions by its lowest value + 1

Possibly affects with a breaking change (doubt it): WeeGet

All of it was automated, with some manual corrections.

Conflicts with any open PR that updates one of these files, but the merge conflicts should be abysmal to fix.

Also replaces http://weechat.org to https://weechat.org

### CODE REVIEW

**Comment by flashcode** [comment]
Thanks for the PR.
For now, I consider it's not a major problem to have an old URL in scripts: it's always in comments or messages displayed, and there's an automatic redirection to the new URL.
Bumping all scripts versions at once for just an URL changed in a message is not really needed now.
I'll take care about scripts updates and change the URL each time a script is updated, if it points to an old URL.

**Comment by de-vri-es** [comment]
For a change this minor, it might even be an option to just change the URL and not bump the version? I presume nothing would break horribly.

**Comment by Zarthus** [comment]
I proposed the same, but FlashCode didn't want to have a checksum change without version bump.

**Comment by flashcode** [comment]
Yes, the script plugin checks new version with the checksum of the file: so if only one byte in the file has changed, the script is marked as obsolete in WeeChat (which means a new version can be instaled). The comparison is not made on the script version.

**Comment by de-vri-es** [comment]
Fair enough. Good day to you both :)

**Pull request closed without merging**
