### PR TITLE
weenotifier.py: notifier using IrssiNotifier

### PR DESCRIPTION
**Pull request by mohan43u**
## Script info

- Script name: weenotifier.py

- Version: 0.0.1

- Requirements: cryptograpy

- Script tags: IrssiNotifier, push, notify

## Description

notifier which is capable of communicating with IrssiNotifier(https://irssinotifier.appspot.com/).  This IrssiNotifier  uses to deliver notifications. This can be a great supplement for weechat-android.

## Checklist (new script)

- [x] Single commit, single file added
- [x] Commit message: `New script name.py: short description…`
- [ ] No similar script already exists
- [x] Name: max 32 chars, only lower case letters, digits and underscores
- [x] Unique name, does not already exist in repository
- [x] No shebang on the first line
- [x] Comment in script with name/pseudo, e-mail and license
- [x] Only English in code/comments
- [x] Pure WeeChat API used, no extra API
- [x] Function `hook_process` is used for any blocking call
- [x] For Python script: works with Python 3 (Python 2 support is optional)

### CODE REVIEW

**Comment by mohan43u** [comment]
@flashcode any chance of getting this approved?

**Comment by Techman** [comment]
@mohan43u, I am not sure if you knew this or not, but it appears a similar script for this functionality already exists as [irssinotifier.py](https://github.com/weechat/scripts/blob/master/python/irssinotifier.py).

**Comment by mohan43u** [comment]
> @mohan43u, I am not sure if you knew this or not, but it appears a similar script for this functionality already exists as [irssinotifier.py](https://github.com/weechat/scripts/blob/master/python/irssinotifier.py).

Yes, I'm aware of that script. Thats why I didn't tick all the checks in checklist. I also tried to use irssinotifier, it didn't work for me. Also, I tried to fix it, but the way it uses openssl commandline to encrypt message may not be the right way to do encryption.

Thats why I wrote a new one. This script doesn't use openssl but uses python's cryptography module to encrypt.

**Comment by mohan43u** [comment]
So, what is required to make this script committed to this repository?

**Comment by weechatter** [comment]
simply wait and be patient!

You can use the script anyway.

**Comment by flashcode** [comment]
Merged, sorry for the delay!

**Pull request merged**
