### PR TITLE
Update weetweet to version 1.2.4

### PR DESCRIPTION
**Pull request by DarkDefender**
Hopefully this pull request is correct this time... :P

### CODE REVIEW

**Comment by DarkDefender** [comment]
I've bumped the version to 1.2.4 because @MatthewCox added some very useful features. :)

**Comment by flashcode** [comment]
Could you please list the new features and bugs fixed in the commit message (short list on one line, with details below if needed)?
Thanks.

**Comment by DarkDefender** [comment]
So something like:
```
weetweet.py 1.2.4: added command link and fav+retweet

link: to get a url to the tweet in question
fav and retweet: A command to fav+rt in one go

Special thanks to MatthewCox for implementing these new
features and some other clean ups.
```
?

**Comment by flashcode** [comment]
Yes.

**Comment by DarkDefender** [comment]
Done :)

**Pull request merged**
