### PR TITLE
Some fixes to mnotify.py

### PR DESCRIPTION
**Pull request by remram44**
These are some fixes I made after installing the script on my machine.

I also opened this against @mmaker's repository, but I don't know if it is still maintained there (the version in here is more recent): mmaker/mnotify#3

### CODE REVIEW

**Comment by remram44** [comment]
The PR has been accepted by the author in his repo, can this be merged in? Anything else I can do?

**Comment by flashcode** [comment]
Could you please increase the version number in script, rebase the 2 commits into a single one and format the commit message like described in Contributing.asciidoc?
Thanks.

**Comment by remram44** [comment]
I'm very much in favor of micro-commits, but whatever. Does this work?

**Comment by flashcode** [comment]
Better, thanks!

**Pull request merged**
