### PR TITLE
add suppress_whitespace.py

### PR DESCRIPTION
**Pull request by kevr**
`suppress_whitespace.py` can be used to remove the ability for
clients to send whitespace-only messages.

It can be used to avoid accidental messages in general.

If a user with an empty input buffer types in any whitespace
characters, it does not include them in the input buffer;
requiring some sort of valid input before whitespace is allowed.

Signed-off-by: Kevin Morris <kevr@0cost.org>

## Script info

- Script name: suppress_whitespace
- Version: 0.0.1

- Requirements:

- Min WeeChat version: 

- Script tags: 

## Checklist (new script)

- [x] Single commit, single file added
- [x] Commit message: `New script name.py: short description…`
- [x] No similar script already exists
- [x] Name: max 32 chars, only lower case letters, digits and underscores
- [x] Unique name, does not already exist in repository
- [x] No shebang on the first line
- [x] Comment in script with name/pseudo, e-mail and license
- [x] Only English in code/comments
- [x] Pure WeeChat API used, no extra API
- [x] Function `hook_process` is used for any blocking call
- [x] For Python script: works with Python 3 (Python 2 support is optional)

### CODE REVIEW

**Comment by kevr** [comment]
Signed with key.

**Comment by weechatter** [comment]
There is an simliar script and trigger.
https://weechat.org/scripts/source/unwanted_msg.py.html/

https://github.com/weechat/weechat/wiki/Triggers#avoid-sending-misformatted-commandsmessages-starting-with-a-space-this-trigger-replaces-the-unwanted_msgpy-script

**Comment by kevr** [comment]
> There is an simliar script and trigger.
> https://weechat.org/scripts/source/unwanted_msg.py.html/
> 
> https://github.com/weechat/weechat/wiki/Triggers#avoid-sending-misformatted-commandsmessages-starting-with-a-space-this-trigger-replaces-the-unwanted_msgpy-script

True, however, that script is apparently for commands only. Notice the regexp `' +/'`. Plus, it looks like it only handles spaces -- I'd recommend a '\s+' instead of ' +'.

This one is for _any_ message in general.

**Comment by weechatter** [comment]
It would be fine to update the existing script than to have two scripts doing almost the same thing, no!?

**Comment by kevr** [comment]
> It would be fine to update the existing script than to have two scripts doing almost the same thing, no!?

If the script author is okay with that, I'd be fine with it.

**Comment by weechatter** [comment]
I would say, its ok. nesthib, the author of script, wrote his last message in #weechat more than 1000 days ago. Seems like, he is not active anymore. I made the script py3 compatible 3 years ago.

**Comment by kevr** [comment]
Alright, I'll have a PR in a day or two for it. Thank you, I appreciate it! (12th-13th). I will close this up when that's up.

**Comment by kevr** [comment]
Actually, forget the day or two.

It's up: https://github.com/weechat/scripts/pull/478

Closing this one. Any feedback is greatly appreciated in the new PR. I'm not sure if I went overboard with removing the warning text or so; I wasn't sure what exact purpose it serves, so I removed them to simplify the script.

**Pull request closed without merging**
