### PR TITLE
colorize_nicks.py: fix nick colorization in input for colon completer

### PR DESCRIPTION
**Pull request by foxxx0**
The global `VALID_NICK` regex allows the nick to contain a colon, however
the nick matching logic with stripping the first/last character is not
used within `#colorize_input_cb()`.
In combination with a colon `:` for `weechat.completion.nick_completer`,
this leads to nicks not being colorized in the input line.

To fix this, we can just always `rstrip()` the currently configured
`nick_completer` character.

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Could you please bump the script version and use the commit message mentioned in the Contributing doc?
Thanks.

**Comment by foxxx0** [comment]
Thanks for the feedback, I updated the PR.
Please check if it now fits the requirements.

**Comment by flashcode** [comment]
Please bump the script version (not only comments), thanks.

**Comment by flashcode** [comment]
Hi,

As #443 was merged, the script version is now 28.
Could you please rebase your changes over this version and bump version to 29?

Thanks.

**Comment by flashcode** [comment]
Hi,
A new version (29) has been uploaded, I close this pull request.
If needed, please open another one, based on the latest version of the script.
Thanks!

**Pull request closed without merging**
