### PR TITLE
autoconnect.py 0.3: save channels on exit, restructure

### PR DESCRIPTION
**Pull request by Tigge**
Previously it was not possible to differentiate between a '/disconnect
network' command and '/quit'. When you disconnect a network you might
not want to save the channel list, but you do want that on quit.

Also restructured the code a bit since the join and part callbacks
shared much code. Now also using a set to keep track of channels and
make add remove a bit easier.

### CODE REVIEW

**Comment by Tigge** [comment]
@arenevier could you take a look at this? I'm mostly trying to fix loosing the `irc.*.autojoin` list on `/quit` -- since the `irc_server_disconnected` signal is called before the `quit` signal since a few weechat versions back. I also did some refactoring to make things more readable and to reuse a bit of code.

**Comment by sim642** [comment]
Please refer to [Contributing.asciidoc](https://github.com/weechat/scripts/blob/master/Contributing.asciidoc#send-new-release) regarding script updates, especially the commit naming part.

**Comment by Tigge** [comment]
@sim642 Sorry about that, I've fixed the commit message and the tile of the PR. A bit unsure if an @-mention here was sufficient to contact the author or if I should have done that outside of GitHub first.

**Comment by arenevier** [comment]
Hi, thanks for contacting me. I don't really have time those days to look at that though. Sorry about that.

**Pull request merged**
