### PR TITLE
allow for utf8 nicks (rfc7613)

### PR DESCRIPTION
**Pull request by lbeziaud**
Colorize UTF-8 nicks. A valid nick may contain `@~&!%+-` in first position, followed by anything but  `<space>,*?.!@`, and can end with `:`. (see #226)

### CODE REVIEW

**Comment by lbeziaud** [comment]
some testing

**Comment by flashcode** [comment]
Hi,
Once finished, please ping me here, and rebase all your commits into a single one (with the appropriate version update and commit message, see the Contributing.adoc file).

**Comment by lbeziaud** [comment]
@flashcode: should be good now.

test2

**Comment by amerlyq** [comment]
@flashcode how you feel about merging it, for example... now ?))

**Comment by flashcode** [comment]
Merged, thanks.

**Pull request closed without merging**
