### PR TITLE
fish.py 0.9.3: fix compatibility with new Crypto

### PR DESCRIPTION
**Pull request by rr-**
Fixes

```
python: stdout/stderr (fish): Traceback (most recent call last):
python: stdout/stderr (fish):   File "/home/rr-/.weechat/python/autoload/fish.py", line 703, in fish_modifier_in_privmsg_cb
python: stdout/stderr (fish):     b = Blowfish(fish_keys[targetl])
python: stdout/stderr (fish):   File "/home/rr-/.weechat/python/autoload/fish.py", line 235, in __init__
python: stdout/stderr (fish):     self.blowfish = Crypto.Cipher.Blowfish.new(key)
python: stdout/stderr (fish): TypeError: new() takes at least 2 arguments (1 given)
python: error in function "fish_modifier_in_privmsg_cb"
```

### CODE REVIEW

**Comment by rr-** [comment]
I could also catch `TypeError` to make sure it stays compatible with the previous crypto version, since I'm not sure if it provides a constructor that takes the second argument.

**Comment by weechatter** [comment]
Is the script also python3 compatible? See, https://weechat.org/scripts/python3/

**Comment by rr-** [comment]
It's not. Should I update it within this pull request, or create a separate pull request for this?

**Comment by flashcode** [comment]
If it does not require too many changes, you can integrate it in this pull request, thanks.

**Comment by rr-** [comment]
Done

**Comment by rr-** [comment]
Ping

**Comment by weechatter** [comment]
pong

**Comment by flashcode** [comment]
Thanks, merged (with update of WeeChat website URL).

**Pull request closed without merging**
