### PR TITLE
mqtt_notify.py: v0.5: major update

### PR DESCRIPTION
**Pull request by srgvg**
A 'big' update and partial rewrite to this script. I have been running and bugfixing it myself for several weeks, and for about a week in it's current version. It seems pretty stable to me.

I added some variables to customize the hook data field, with defaults that are backwards compatible.
Other changes should not have any impact on the functionality, not breaking client side scripts. I basically only added some keys to the message `json`, but kept everything  that existed as is.

- checks: autopep8 validated
- feature: add variables to customize the data fiels in the
  print hooks, default values are backwards compatible
- feature: add messages on connecting/disconnecting to mqtt
- feature: add script unload hook function to clean up the mqtt
  connection
- feature: add variable for mqtt client name
- feature: add buffer_long and buffer_full in message json
- fix: move mqtt connect code to global scope, avoiding
  new connections on each message causing lost messages due to
  network/socket errors, and optimized for mqtt client
  loop_start/stop
- fix: rename mqtt_timeout to mqtt_keepalive

### CODE REVIEW

**Comment by srgvg** [comment]
I mentioned myself as new maintainer for this script, in the comments, as confirmed to me by original author @maethor. I'll ping him and ask him to confirm also here.

As original `SCRIPT_AUTHOR` must be preserved, I also added `SCRIPT_MAINTAINER`. Might be an idea to extend on the overview page?

**Comment by maethor** [comment]
I confirm I'm not interesting in maintaining this script anymore. Considering the size of the rewrite, @srgvg should be displayed as maintainer or co-author.

**Comment by srgvg** [comment]
fyi, I also have a client side script that takes the messages of the mqtt queue en does libnotify: https://github.com/srgvg/dotfiles/blob/master/bin/mqtt-notify.py - can help to test.

**Comment by srgvg** [comment]
Fixed as requested.

**Pull request merged**
