### PR TITLE
port some scripts to python3

### PR DESCRIPTION
**Pull request by TauPan**
Those are python3 only now...

### CODE REVIEW

**Comment by trygveaa** [comment]
From a quick glance, there seems to be very few python 2 incompatible changes in the scripts. I think `country.py` just needs `from __future__ import print_function` to be compatible with python 2. And apart from that, the only incompatible change I see are the two `encode`/`decode` changes.

**Comment by TauPan** [comment]
You're probably right. I was a bit lazy yesterday. But since country.py only does ipv4 it's becoming increasingly useless these days. Also some of the  features of autoconnect are provided by /upgrade -quit . Not really sure what to do with these scripts.

**Comment by flashcode** [comment]
Hi @TauPan,

Thanks for the updates and the help to port scripts to Python 3.

Two things about this PR:

1. Please open one pull request per script (see file https://github.com/weechat/scripts/blob/master/Contributing.adoc)
2. For now, the scripts must be compatible with Python 2 **and** 3, see the page about the transition to Python 3: https://weechat.org/scripts/python3/

I close this PR, please open a separate PR for each script to update.

**Comment by TauPan** [comment]
> Hi @TauPan,
> 
> Thanks for the updates and the help to port scripts to Python 3.
> 
> Two things about this PR:
> 
> 1. Please open one pull request per script and follow the commit messages described in this file: https://github.com/weechat/scripts/blob/master/Contributing.adoc
> 2. For now, the scripts must be compatible with Python 2 **and** 3, see the page about the transition to Python 3: https://weechat.org/scripts/python3/
> 
> I close this PR, please open a separate PR for each script to update.

Hi! thanks for your feedback and information! Apologies for not checking the documentation first.

Are there any automatic tests to check scripts with python2 and python3? I'd like to open a pull request for tmux_env.py. I'm not going to do the others.

**Comment by weechatter** [comment]
Check if script is compatible with python3 (https://weechat.org/scripts/stable/language/python3-compatible/), if not open an issue and send your pull request.

Would be great to check if script can be replaced by a /trigger, for example. Then the
script can be remove from repository.

**Comment by flashcode** [comment]
@TauPan : you can follow instructions on this page to test with Python 2 & 3: https://weechat.org/scripts/python3/

**Pull request closed without merging**
