### PR TITLE
fish.py: fix key exchange

### PR DESCRIPTION
**Pull request by wikro**
Exchanging keys with current version of fish.py (0.9.4) results in errors because sometimes bytes objects are passed to functions, sometimes string objects.

### CODE REVIEW

**Comment by wikro** [comment]
@rr- Your repo was a bit old, hence why I sent a PR straight here

**Comment by flashcode** [comment]
Hi,
There are no changes in this pull request?

**Comment by wikro** [comment]
The changes were merged to master on Aug 2. If you check the commits you can see my changes. I also saw change #425, which fixes my fix even further, and probably more correctly.

**Comment by Xtravaganz** [comment]
Someone has the knowledge to add a CBC mode?

**Comment by flashcode** [comment]
It should be already fixed by #425, closing this MR.

**Pull request closed without merging**
