### PR TITLE
only parse emoji in :trailing params and fix py3 bytes vs str issue

### PR DESCRIPTION
**Pull request by jesopo**
these two problems just came together for someone on freenode to create this:

`=!= :andril!~andril@2601:586:8400b'\xf0\x9f\x85\xb0' d6b9:a1f2:8545:a4c3 QUIT :Ping timeout: 256 seconds`

from a user with a hostmask of `:andril!~andril@2601:586:8400:a:d6b9:a1f2:8545:a4c3`

### CODE REVIEW

**Comment by jesopo** [comment]
just found #231 and, in doing so, noticed something I have not yet fixed.

**Comment by jesopo** [comment]
ready for review

**Comment by flashcode** [comment]
Hi,
Could you please rebase/squash all your commits in a single one, use the commit message described in the Contributing file and bump the script version?
Thanks.

**Comment by jesopo** [comment]
done.

**Pull request merged**
