### PR TITLE
lnotify.py 0.35: fix malformed `ps` call with py3

### LINKED ISSUE #334: lnotify 0.34 + Python 3.7: malformed ps call
`subprocess.check_output()` returns `bytes`.
The result of the call on line 103 (bytes) is then used to form the command passed to another call of `subprocess.check_output()` on the following line.

This fails on Python 3.

When lnotify is run on Python 2, the shell command on line 104 is obtained by using `%` string formatting (a Python 2 default), with a `bytes` object used as the value of the singular `%s`. This provides a clean output in Python 2 (say, since it's a PID, `1102`) and a mangled one in Python 3 : `b'1102'`, since there is no implicit bytes -> str conversion (apart from bytes' `__str__`).

`window_pid`, the `bytes` instance, must be converted to `str` (unicode string) in Python 3, before using it as an argument to `%`.

I'll submit a PR fixing this using `from __future__ import unicode_literals`.

### PR DESCRIPTION
**Pull request by randrej**
This fixes #334. Please, test it on Python 2, too.

### CODE REVIEW

**Comment by weechatter** [comment]
please bump version number:
lnotify_version = "0.3.4"

**Comment by flashcode** [comment]
And please use the commit message mentioned in the file [Contributing.adoc](https://github.com/weechat/scripts/blob/master/Contributing.adoc).

**Comment by randrej** [comment]
Changed title + version.

**Comment by sadsfae** [comment]
This works for me, tested on Python 3.7.3

**Comment by flashcode** [comment]
Thanks, merged.

**Pull request closed without merging**
