### PR TITLE
grep.py: make it work with python3

### PR DESCRIPTION
**Pull request by jpmenil**

### CODE REVIEW

**Comment by jpmenil** [comment]
Hmm, seem that i misread the following web page:
https://weechat.org/scripts/python3/

Need to be sure that it is also python2 compatible.

**Comment by jpmenil** [comment]
Working in python2 mode too.

**Comment by jpmenil** [comment]
@flashcode sure, just see them, will work on it.

**Comment by flashcode** [comment]
Hi @jpmenil,
I still see some use of "sorted" and changes in exception message, did you push all your changes?
Thanks.

**Comment by flashcode** [comment]
Hi,
Thanks for the commit, but I still see 3 changes with a "sorted", which are bugs for me.

**Comment by sim642** [comment]
Given that `grep.py` was made Python 3 compatible in https://github.com/weechat/scripts/commit/b8394d6797f6db4bb985bf5f336905450ba51446#diff-295167b32f8c04a4b21ad2263b479988, this PR is unnecessary.

**Pull request closed without merging**
