### PR TITLE
Replace `apply string-append` with `string-join`.

### PR DESCRIPTION
**Pull request by yuvallangerontheroad**
## Script info

- Script name: emote.scm
- Version: 0.3.1

- Requirements: 

- Min WeeChat version: 

- Script tags: 

## Description

Simplifying the code by using a procedure designed to be given a list, rather than applying a procedure designed to be given many arguments.

## Checklist (new script)

- [ ] Single commit, single file added
- [ ] Commit message: `New script name.py: short description…`
- [ ] No similar script already exists
- [ ] Name: max 32 chars, only lower case letters, digits and underscores
- [ ] Unique name, does not already exist in repository
- [ ] No shebang on the first line
- [ ] Comment in script with name/pseudo, e-mail and license
- [ ] Only English in code/comments
- [ ] Pure WeeChat API used, no extra API
- [ ] Function `hook_process` is used for any blocking call
- [ ] For Python script: works with Python 3 (Python 2 support is optional)
- [ ] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

## Checklist (script update)

- [ ] Author has been contacted
- [ ] Single commit, single file added
- [ ] Commit message format: `script_name.py X.Y: …`
- [ ] Script version and Changelog have been updated
- [ ] For Python script: works with Python 3 (Python 2 support is optional)
- [ ] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

## Checklist (script deletion)

- [ ] Author has been contacted
- [ ] Single commit, single file deleted
- [ ] Commit message format: `Remove script name.py` with reasons in description

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Please tick the checkboxes in the "Checklist (script update)" and ensure this is applied (for example you have to bump the script version for any change in the script, even minor).
If a task is not done, please explain why.
I'll merge as soon as this is done, changes are OK for me.
Thanks!

**Comment by yuvallangerontheroad** [comment]
> Hi, Please tick the checkboxes in the "Checklist (script update)" and ensure this is applied (for example you have to bump the script version for any change in the script, even minor). If a task is not done, please explain why. I'll merge as soon as this is done, changes are OK for me. Thanks!

Oh! This is a drive-by patch. I just saw something a bit weird and wanted to change it. I would have to contact the author now…

**Comment by calebsmith** [comment]
@yuvallangerontheroad This change looks good. More than happy to accept this. Per the checklist, I think you need the script name in the commit message. Once you tweak that message I'm happy to see it merged.

Thanks for your help!

**Comment by flashcode** [comment]
Commit reworded and merged, thanks!

**Pull request closed without merging**
