### PR TITLE
spotify.py: Update script for new web api

### PR DESCRIPTION
**Pull request by creadak**

### CODE REVIEW

**Comment by torhve** [comment]
+1 looks good to me

**Comment by creadak** [comment]
Found a bug, it seems to post the lines to the active buffer, not the buffer the spotify URI was posted in. Fixing now

**Comment by flashcode** [comment]
@creadak : could you please rebase all your commits in a single one, and use the git format message described in file Contributing.asciidoc?
Thanks.

**Comment by creadak** [comment]
Rebased, if there's anything else that needs to be changed let me know

**Pull request merged**
