### PR TITLE
Fish.py Python 3

### PR DESCRIPTION
**Pull request by rr-**
Fixes fish.py for Python 3. Python 2 compat lost.

Closes https://github.com/weechat/scripts/issues/384
Alternative implementation to https://github.com/weechat/scripts/pull/398

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Thanks for the PR.
What's different from #398, something was wrong in this PR?

**Comment by rr-** [comment]
@flashcode

1. I didn't know the PR existed before making this change, as I couldn't find anything with `fish` in the pull requests.
2. The other PR has more complex changes, whereas I decided to go with minimum changes necessary, plus I fix `MalformedError` not being defined. I also introduce Black formatting. Other than that, the PRs are identical.

- https://github.com/weechat/scripts/pull/398/files
- https://github.com/weechat/scripts/pull/406/commits/3c0e8762ece6505192a76f5bacd02282b095cf55

**Comment by nikster2** [comment]
This version of the script does not work for me. This was the reason I made the other version. I only get these errors all the time with this 0.9.4 version.

                 │15:58:20 weechat =!= | python: error in function "fish_modifier_in_privmsg_cb"
                 │15:58:28 weechat     | python: stdout/stderr (fish): Traceback (most recent call last):
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 868, in fish_modifier_in_privmsg_cb
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 380, in __init__
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.7/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
                 │15:58:28 weechat     | python: stdout/stderr (fish):     return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.7/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
                 │15:58:28 weechat     | python: stdout/stderr (fish):     return modes[mode](factory, **kwargs)
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 215, in _create_ecb_cipher
                 │15:58:28 weechat     | python: stdout/stderr (fish):     cipher_state = factory._create_base_cipher(kwargs)
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.7/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
                 │15:58:28 weechat     | python: stdout/stderr (fish):     result = start_operation(c_uint8_ptr(key),
                 │15:58:28 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.7/site-packages/Crypto/Util/_raw_api.py", line 144, in c_uint8_ptr
                 │15:58:28 weechat     | python: stdout/stderr (fish):     raise TypeError("Object type %s cannot be passed to C code" % type(data))
                 │15:58:28 weechat     | python: stdout/stderr (fish): TypeError: Object type <class 'str'> cannot be passed to C code

**Comment by flashcode** [comment]
@nikster2: could you please create a pull request with your version? So we can compare both.

Or a better solution would be to work on a single PR, currently there are 3 versions of the script to support Python 3, I'm not sure which one should be used…

**Comment by flashcode** [comment]
@nikster2: I merged this PR. If you think an additional fix is needed, please open another PR.

**Comment by nikster2** [comment]
I really don't care. This version doesn't work for me so good for them who are able to use it. I just shared my version which works for me. If no one needs it, that's fine. I'll just use it anyways :)

**Comment by flashcode** [comment]
@nikster2: yes you sen it but using the form, so I can see it but nobody else. And I've not enough time to fully test everything I receive (scripts updates, bug reports, etc.). If you make a PR, this can be tested and commented by other people, much better.

**Pull request closed without merging**
