### PR TITLE
notify.py: Convert to Python 3 using 2to3

### PR DESCRIPTION
**Pull request by rbalint**

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Why did you close this PR?

**Comment by rbalint** [comment]
I've tested the change on Ubuntu 20.04 and while notifications started working weechat hang on exit doing futex() calls. I have not triaged that further, and may not do so soon, but feel free to check it.

**Comment by weechatter** [comment]
not possible with an /trigger?

**Comment by flashcode** [comment]
Merged with some minor changes, thanks.

**Pull request closed without merging**
