### PR TITLE
irssi_awaylog.py: small change to get this work with Python3

### PR DESCRIPTION
**Pull request by vmiklos**
This works fine with Python3, just need to change print "" to print(...).

flake8 points out indentation is done with tabs & there are other small problems with the script, but let's do one step at a time, I guess. :-)

## Script info

- Script name: irssi_awaylog.py
- Version: 0.3

- Script tags: irc, away, log, py3

## Description

Small change to get this to work with Python3.

## Checklist (script update)

- [x] Author has been contacted: I mailed @hrkfdn , though it looks likely there is no external git repo for this script.
- [X] Single commit, single file updated
- [X] Commit message format: `script_name.py: …`
- [ ] Script version and Changelog have been updated: not done, but I can bump the version to 0.4 if wanted.
- [x] For Python script: works with Python 3 (Python 2 support is optional): yes, that's the whole point of this PR
- [X] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint): yes, hence the URL change.

### CODE REVIEW

**Comment by hrkfdn** [comment]
Thanks for migrating it @vmiklos, looks good to me :)

**Comment by flashcode** [comment]
Hi,
Thanks for the update, please update as well script version and changelog (and please merge commits in a single one).
Thanks.

**Comment by vmiklos** [comment]
I added some initial changelog based on what I saw in e.g. chanop.py, hope that format is fine. Thanks.

**Comment by flashcode** [comment]
Ah, if there was no changelog maybe it's not needed then.
All changes are tracked via git commits anyway.

**Comment by vmiklos** [comment]
>  All changes are tracked via git commits anyway.

Agreed, I just dropped the manual history, so now just the small print fix + version bump.

**Comment by flashcode** [comment]
Thanks, merged!

**Pull request closed without merging**
