### PR TITLE
buffer_dmenu.py 0.2.1: add support for fzf-tmux

### PR DESCRIPTION
**Pull request by Seirdy**
fzf-tmux is a script included with FZF:
junegunn/fzf@master/bin/fzf-tmux

Included a link to a screenshot to showcase it.

### CODE REVIEW

**Comment by Seirdy** [comment]
Attempted to contact script author @Ferus as per Contributing.adoc; received email bounceback.

**Comment by weechatter** [comment]
script name is buffer_dmenu.py, script version not bumped.

**Comment by Seirdy** [comment]
On Fri, Mar 19, 2021 at 10:07:03PM -0700, Nils Görs wrote:
>script name is buffer_dmenu.py, script version not bumped.

Oops. Fixed with a force-push.

-- 
/Seirdy

**Comment by flashcode** [comment]
Squashed and merged, thanks!

**Pull request closed without merging**
