### PR TITLE
Updated autopong to Python3.

### PR DESCRIPTION
**Pull request by Heisenburg01**
Contacted Will Clouser - author.  OK

### CODE REVIEW

**Comment by weechatter** [comment]
script is not needed anymore, you can easily use a /trigger to create this function:
https://github.com/weechat/weechat/wiki/Triggers#auto-respond-with-pong-to-ping-queries

**Comment by Heisenburg01** [comment]
Should this script be removed from the repository?

**Comment by weechatter** [comment]
i would recommend, yes.

**Comment by Heisenburg01** [comment]
I removed autopong.py from the more recent commit.  If this is OK with everyone, then merge and close.  Thanks.

**Pull request closed without merging**
