### PR TITLE
New script read_marker.py: draft/read-marker extension support

### PR DESCRIPTION
**Pull request by emersion**
## Script info

- Script name: read_marker
- Version: 0.1.0
- Requirements: none
- Min WeeChat version: none
- Script tags: irc, buffer

## Description

This script adds support for the draft/read-marker IRCv3 extension: https://ircv3.net/specs/extensions/read-marker

## Checklist (new script)

- [x] Single commit, single file added
- [x] Commit message: `New script name.py: short description…`
- [x] No similar script already exists
- [x] Name: max 32 chars, only lower case letters, digits and underscores
- [x] Unique name, does not already exist in repository
- [x] No shebang on the first line
- [x] Comment in script with name/pseudo, e-mail and license
- [x] Only English in code/comments
- [x] Pure WeeChat API used, no extra API
- [x] Function `hook_process` is used for any blocking call
- [x] For Python script: works with Python 3 (Python 2 support is optional)
- [x] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

### CODE REVIEW

**Comment by emersion** [comment]
@flashcode gentle ping

**Comment by flashcode** [comment]
@emersion: thanks for the script, could you please add a comment in the script, explaining how it works, and what's the benefit for the user to use this read marker?

And I think in future such feature should be in WeeChat itself.

**Comment by emersion** [comment]
Done.

> And I think in future such feature should be in WeeChat itself.

Nice. https://github.com/weechat/weechat/issues/1791 tracks this.

**Comment by emersion** [comment]
Gentle ping

**Comment by emersion** [comment]
Thanks!

**Pull request merged**
