### PR TITLE
grep: Change insensible → insensitive

### PR DESCRIPTION
**Pull request by raine**

### CODE REVIEW

**Comment by flashcode** [comment]
Hi,
Please update as well the script version (any change, even a small typo, must be done in a new script version, so that users upgrading scripts will see a new version in WeeChat).

**Comment by raine** [comment]
Can you elaborate which file I need to update?

**Comment by stfnm** [comment]
@raine Same file, line 203 where it says SCRIPT_VERSION.

**Comment by raine** [comment]
Looks good?

**Comment by flashcode** [comment]
Merged.

**Pull request closed without merging**
