### PR TITLE
autojoinem.py 0.7: fix help to take advantage of evaluation in allchan

### PR DESCRIPTION
**Pull request by pascalpoitras**
fix help

### CODE REVIEW

**Comment by weechatter** [comment]
thanks...

**Comment by flashcode** [comment]
@pascalpoitras: you should mention that this example works only with Weechat ≥ 3.0.

**Comment by weechatter** [comment]
flashcode, the brain :-) but its correct, maybe two examples.

**Comment by pascalpoitras** [comment]
@flashcode done

**Comment by pascalpoitras** [comment]
@weechatter i keep the original example and added the one that works only with ≥ 3.0.

**Comment by flashcode** [comment]
By the way, I wonder if it's not the script job to do that, what about adding a command like `/autojoinem addall` that auto adds all opened channels?
And if done like that, the script can check itself if WeeChat version is ≥ 3.0 and use the evaluated version if needed.

**Pull request closed without merging**
