### PR TITLE
jabber.py: call attention support

### PR DESCRIPTION
**Pull request by aelmahmoudy**
Add XEP-0224 call attention (/jattn) command

TODO:
* use disco to check if other party has call attention enabled

### CODE REVIEW

**Comment by weechatter** [comment]
Thanks for the worl. but you know that bitlbee is recommended for jabber support? ;-)

**Comment by aelmahmoudy** [comment]
On Tue, Mar 19, 2019 at 11:10:16PM -0700, Nils Görs wrote:
> Thanks for the worl. but you know that bitlbee is recommended for jabber support? ;-)
---end quoted text---

bitlbee is not an option for some cases

-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints:
 6E2E E4BB 72E2 F417 D066  6ABF 7B30 B496 A7EF 5761
 8206 A196 2084 7E6D 0DF8  B176 BC19 6A94 EDDD A1B7

**Comment by flashcode** [comment]
Hi,

Could you please merge your 3 PR: #325 (this one), #326 and #329?
Currently, #326 can not be applied after this one (not compatible).
I'm closing the 3 PR for now, waiting for a new one.

Thanks.

**Comment by flashcode** [comment]
And if you send a new PR, please bump the script version and update the ChangeLog.

As @weechatter said, Bitlbee is recommended over this script which has some lacks, for example it can freeze WeeChat during network communication (due to the fact it's not made with asynchronous calls).

**Pull request closed without merging**
