### PR TITLE
soju.py 0.4.0: from ssl to tls on weechat >= 4.0.0

### PR DESCRIPTION
**Pull request by stacyharper**
## Script info

- Script name:  soju.py
- Version: 0.4.0

## Description

Fix a compatibility problem with weechat 4.0.0

## Checklist (script update)

- [x] Author has been contacted
- [x] Single commit, single file added
- [x] Commit message format: `script_name.py X.Y: …`
- [x] Script version and Changelog have been updated
- [x] For Python script: works with Python 3 (Python 2 support is optional)
- [x] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

### CODE REVIEW

**Comment by emersion** [comment]
Maybe we can only bump the version number to 0.3.1, since this is just a bugfix?

Anyways, LGTM, thanks for submitting a PR!

**Comment by flashcode** [comment]
Oops, just saw your comment, merged anyway.
Not really a bug, just following changes in WeeChat itself.

**Comment by emersion** [comment]
Right, what I meant is that this new version doesn't add any new functionality to the script.

It's not a big deal, so no worries!

**Comment by flashcode** [comment]
Yes, right, next time I'll wait a bit before merging :)

**Pull request merged**
